development:
  password: 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
  theme_id: "125301227706"
  store: sandar-test.myshopify.com
production:
  password: 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
  theme_id: "125295591610"
  store: sandar-test.myshopify.com
staging:
  password: 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
  theme_id: "125295591610"
  store: sandar-test.myshopify.com
